This is either an incredible idea or the worst thing I've ever written

diff --git a/.github/workflows/freertos_demos.yml b/.github/workflows/freertos_demos.yml
--- a/.github/workflows/freertos_demos.yml
+++ b/.github/workflows/freertos_demos.yml
@@ -441,13 +441,28 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-          demo: [ubuntu-latest, windows-latest]
+          configuration: 
+            [ 
+            { demo: CORTEX_MPU_M3_MPS2_QEMU_GCC, makeArgs: -j},
+            { demo: CORTEX_LM3S102_GCC,       buildCMD: make clean && make -j},
+            { demo: CORTEX_M3_MPS2_QEMU_GCC,  buildCMD: make clean && make -j },
+            { demo: CORTEX_M3_MPS2_QEMU_GCC,  buildCMD: make clean && make -j FULL_DEMO=1 },
+            { demo: CORTEX_LM3S811_GCC,       buildCMD: make clean && make -j },
+            { demo: CORTEX_MPS2_QEMU_IAR_GCC, buildCMD: git clone "https://github.com/raspberrypi/pico-sdk.git";
+                                                        cmake -B build -DPICO_SDK_PATH=pico-sdk -GNinja;
+                                                        ninja -C build --verbose; },
+            { demo: CORTEX_M0+_RP2040,        buildCMD: make clean && make -j, path: ThirdParty/Community-Supported-Demos } 
+          ]
+          include:
+            # For the CORTEX_M3_MPS2_QEMU_GCC add in the blinky and non-blinky demo
+            - demo: ThirdParty/Community-Supported-Demos/CORTEX_M0+_RP2040
+              matrix: 
+                makeOptions: [FULL, BLINKY]
     steps:
       - env:
           stepName: Checkout Repository
         name: ${{ env.stepName }}
         uses: actions/checkout@v3
-
       
       - env:
           stepName: Fetch Kernel Submodule
@@ -487,15 +502,18 @@ jobs:
           fi
 
       - env:
-          stepName: Build CORTEX_MPU_M3_MPS2_QEMU_GCC Demo
-        name: ${{ env.stepName }}
+          stepName: Build ${{ matrix.configuration.demo}} Demo
+        name: ${{ env.stepName}}
         shell: bash
-        working-directory: FreeRTOS/Demo/CORTEX_MPU_M3_MPS2_QEMU_GCC
+        working-directory: FreeRTOS/Demo/${{ matrix.configuration.demo }}
         run: |
           # ${{ env.stepName }}
           echo "::group::${{ env.stepName }}"
           set +e
-          make -j
+          if [[ -d "${{ matrix.configuration.path }}" ]]; then
+            cd ${{ matrix.configuration.path }}
+          fi
+          ${{ matrix.configuration.buildCMD }}
           exitStatus=$?
           echo "::endgroup::"
           if [ "$exitStatus" = "0" ]; then
@@ -505,121 +523,121 @@ jobs:
             exit 1
           fi
 
-      - env:
-          stepName: Build CORTEX_LM3S102_GCC Demo
-        name: ${{ env.stepName }} 
-        shell: bash
-        working-directory: FreeRTOS/Demo/CORTEX_LM3S102_GCC
-        run: |
-          # ${{ env.stepName }}
-          echo "::group::${{ env.stepName }}"
-          set +e
-          make clean
-          make -j
-          exitStatus=$?
-          echo "::endgroup::"
-          if [ "$exitStatus" = "0" ]; then
-            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
-          else
-            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
-            exit 1
-          fi
+#      - env:
+#          stepName: Build CORTEX_LM3S102_GCC Demo
+#        name: ${{ env.stepName }} 
+#        shell: bash
+#        working-directory: FreeRTOS/Demo/CORTEX_LM3S102_GCC
+#        run: |
+#          # ${{ env.stepName }}
+#          echo "::group::${{ env.stepName }}"
+#          set +e
+#          make clean
+#          make -j
+#          exitStatus=$?
+#          echo "::endgroup::"
+#          if [ "$exitStatus" = "0" ]; then
+#            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+#          else
+#            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+#            exit 1
+#          fi
 
-      - env:
-          stepName: Build CORTEX_M3_MPS2_QEMU_GCC Demo
-        name: ${{ env.stepName }}
-        shell: bash
-        working-directory: FreeRTOS/Demo/CORTEX_M3_MPS2_QEMU_GCC
-        run: |
-          # ${{ env.stepName }}
-          echo "::group::${{ env.stepName }}"
-          set +e
-          make clean
-          make -j
-          exitStatus=$?
-          echo "::endgroup::"
-          if [ "$exitStatus" = "0" ]; then
-            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
-          else
-            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
-            exit 1
-          fi
+#      - env:
+#          stepName: Build CORTEX_M3_MPS2_QEMU_GCC Demo
+#        name: ${{ env.stepName }}
+#        shell: bash
+#        working-directory: FreeRTOS/Demo/CORTEX_M3_MPS2_QEMU_GCC
+#        run: |
+#          # ${{ env.stepName }}
+#          echo "::group::${{ env.stepName }}"
+#          set +e
+#          make clean
+#          make -j
+#          exitStatus=$?
+#          echo "::endgroup::"
+#          if [ "$exitStatus" = "0" ]; then
+#            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+#          else
+#            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+#            exit 1
+#          fi
 
-      - env:
-          stepName: Build CORTEX_M3_MPS2_QEMU_GCC Full Demo
-        name: ${{ env.stepName }}
-        shell: bash
-        working-directory: FreeRTOS/Demo/CORTEX_M3_MPS2_QEMU_GCC
-        run: |
-          # ${{ env.stepName }}
-          echo "::group::${{ env.stepName }}"
-          set +e
-          make clean
-          make FULL_DEMO=1 -j
-          exitStatus=$?
-          echo "::endgroup::"
-          if [ "$exitStatus" = "0" ]; then
-            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
-          else
-            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
-            exit 1
-          fi
+#      - env:
+#          stepName: Build CORTEX_M3_MPS2_QEMU_GCC Full Demo
+#        name: ${{ env.stepName }}
+#        shell: bash
+#        working-directory: FreeRTOS/Demo/CORTEX_M3_MPS2_QEMU_GCC
+#        run: |
+#          # ${{ env.stepName }}
+#          echo "::group::${{ env.stepName }}"
+#          set +e
+#          make clean
+#          make FULL_DEMO=1 -j
+#          exitStatus=$?
+#          echo "::endgroup::"
+#          if [ "$exitStatus" = "0" ]; then
+#            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+#          else
+#            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+#            exit 1
+#          fi
 
-      - env:
-          stepName: Build CORTEX_LM3S811_GCC Demo
-        name: ${{ env.stepName }}
-        shell: bash
-        working-directory: FreeRTOS/Demo/CORTEX_LM3S811_GCC
-        run: |
-          # ${{ env.stepName }}
-          echo "::group::${{ env.stepName }}"
-          set +e
-          make -j
-          exitStatus=$?
-          echo "::endgroup::"
-          if [ "$exitStatus" = "0" ]; then
-            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
-          else
-            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
-            exit 1
-          fi
+#      - env:
+#          stepName: Build CORTEX_LM3S811_GCC Demo
+#        name: ${{ env.stepName }}
+#        shell: bash
+#        working-directory: FreeRTOS/Demo/CORTEX_LM3S811_GCC
+#        run: |
+#          # ${{ env.stepName }}
+#          echo "::group::${{ env.stepName }}"
+#          set +e
+#          make -j
+#          exitStatus=$?
+#          echo "::endgroup::"
+#          if [ "$exitStatus" = "0" ]; then
+#            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+#          else
+#            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+#            exit 1
+#          fi
 
-      - env:
-          stepName: Build CORTEX_M0+_RP2040 Demos
-        name: ${{ env.stepName }}
-        shell: bash
-        working-directory: FreeRTOS/Demo/ThirdParty/Community-Supported-Demos/CORTEX_M0+_RP2040
-        run: |
-          # ${{ env.stepName }}
-          echo "::group::${{ env.stepName }}"
-          set +e
-          git clone https://github.com/raspberrypi/pico-sdk.git
-          cmake -B build -DPICO_SDK_PATH=pico-sdk -GNinja
-          ninja -C build --verbose
-          exitStatus=$?
-          echo "::endgroup::"
-          if [ "$exitStatus" = "0" ]; then
-            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
-          else
-            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
-            exit 1
-          fi
+#      - env:
+#          stepName: Build CORTEX_M0+_RP2040 Demos
+#        name: ${{ env.stepName }}
+#        shell: bash
+#        working-directory: FreeRTOS/Demo/ThirdParty/Community-Supported-Demos/CORTEX_M0+_RP2040
+#        run: |
+#          # ${{ env.stepName }}
+#          echo "::group::${{ env.stepName }}"
+#          set +e
+#          git clone https://github.com/raspberrypi/pico-sdk.git
+#          cmake -B build -DPICO_SDK_PATH=pico-sdk -GNinja
+#          ninja -C build --verbose
+#          exitStatus=$?
+#          echo "::endgroup::"
+#          if [ "$exitStatus" = "0" ]; then
+#            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+#          else
+#            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+#            exit 1
+#          fi
 
-      - env:
-          stepName: Build CORTEX_MPS2_QEMU_IAR_GCC Demo
-        name: ${{ env.stepName }}
-        shell: bash
-        working-directory: FreeRTOS/Demo/CORTEX_MPS2_QEMU_IAR_GCC
-        run: |
-          # ${{ env.stepName }}
-          echo "::group::${{ env.stepName }}"
-          set +e
-          make -C build/gcc -j
-          exitStatus=$?
-          echo "::endgroup::"
-          if [ "$exitStatus" = "0" ]; then
-            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
-          else
-            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
-            exit 1
-          fi
+#      - env:
+#          stepName: Build CORTEX_MPS2_QEMU_IAR_GCC Demo
+#        name: ${{ env.stepName }}
+#        shell: bash
+#        working-directory: FreeRTOS/Demo/CORTEX_MPS2_QEMU_IAR_GCC
+#        run: |
+#          # ${{ env.stepName }}
+#          echo "::group::${{ env.stepName }}"
+#          set +e
+#          make -C build/gcc -j
+#          exitStatus=$?
+#          echo "::endgroup::"
+#          if [ "$exitStatus" = "0" ]; then
+#            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+#          else
+#            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+#            exit 1
+#          fi
