Had another command meant for bash in a pwsh section

diff --git a/.github/workflows/freertos_demos.yml b/.github/workflows/freertos_demos.yml
--- a/.github/workflows/freertos_demos.yml
+++ b/.github/workflows/freertos_demos.yml
@@ -5,14 +5,14 @@ on:
   workflow_dispatch:
 
 env:
-  bashPass:   \033[32;1mPASSED  -
+  bashPass:   \033[32;1mPASSED -
   bashWarn:   \033[33;1mWARNING -
-  bashFail:   \033[31;1mFAILED  -
+  bashFail:   \033[31;1mFAILED -
   bashEnd:    \033[0m
 
-  pwshPass:   '`e[32;1mPASSED  -'
+  pwshPass:   '`e[32;1mPASSED -'
   pwshWarn:   '`e[33;1mWARNING -'
-  pwshFail:   '`e[31;1mFAILED  -'
+  pwshFail:   '`e[31;1mFAILED -'
   pwshEnd:    '`e[0m'
 
 
@@ -33,9 +33,9 @@ jobs:
         shell: bash
         run: |
           # ${{ env.stepName }}
-          echo -e "${{ env.bashPass }} Test Windows Bash Pass Colour     ${{ env.bashEnd }}"
-          echo -e "${{ env.bashWarn }} Test Windows Bash Warning Colour  ${{ env.bashEnd }}"
-          echo -e "${{ env.bashFail }} Test Windows Bash Fail Colour     ${{ env.bashEnd }}"
+          echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+          echo -e "${{ env.bashWarn }} ${{ env.stepName }} ${{ env.bashEnd }}"
+          echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
           
       - env:
           stepName: Test Windows Pwsh Colours
@@ -53,7 +53,7 @@ jobs:
         shell: bash
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           set +e
           git submodule update --checkout --init --depth 1 FreeRTOS/Source
           exitStatus=$?
@@ -78,7 +78,7 @@ jobs:
         working-directory: FreeRTOS/Demo/WIN32-MSVC
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           $content = Get-Content -Path 'main.c' -Raw
           $newContent = $content -replace 'int\s+main(.*?)void(.*?)\r?\n\s*{', 'int main( void ){setvbuf( stdout, NULL, _IONBF, 0 );'
           $newContent | Set-Content -Path 'main.c'
@@ -109,7 +109,7 @@ jobs:
         working-directory: FreeRTOS/Demo/WIN32-MSVC
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           $content = Get-Content -Path 'main.c' -Raw
           $newContent = $content -replace '#define\s+mainCREATE_SIMPLE_BLINKY_DEMO_ONLY\s+0', '#define mainCREATE_SIMPLE_BLINKY_DEMO_ONLY    1'
           $newContent | Set-Content -Path 'main.c'
@@ -140,12 +140,12 @@ jobs:
         working-directory: FreeRTOS/Demo/WIN32-MSVC-Static-Allocation-Only
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           $content = Get-Content -Path 'main.c' -Raw
           $newContent = $content -replace 'int\s+main(.*?)void(.*?)\r?\n\s*{', 'int main( void ){setvbuf( stdout, NULL, _IONBF, 0 );'
           $newContent | Set-Content -Path 'main.c'
           msbuild WIN32.sln -t:rebuild
-          exitStatus=$?
+          $exitStatus = $?
           echo "::endgroup::"
           if($exitStatus -eq 1) {
             echo "${{ env.pwshPass }} ${{ env.stepName }} ${{ env.pwshEnd }}"
@@ -178,7 +178,7 @@ jobs:
         shell: bash
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           set +e
           git submodule update --checkout --init --depth 1 FreeRTOS/Source
           exitStatus=$?
@@ -197,7 +197,7 @@ jobs:
         working-directory: FreeRTOS/Demo/WIN32-MingW
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           $content = Get-Content -Path 'main.c' -Raw
           $newContent = $content -replace 'int\s+main(.*?)void(.*?)\r?\n\s*{', 'int main( void ){setvbuf( stdout, NULL, _IONBF, 0 );'
           $newContent | Set-Content -Path 'main.c'
@@ -229,7 +229,7 @@ jobs:
         working-directory: FreeRTOS/Demo/WIN32-MingW
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           $content = Get-Content -Path 'main.c' -Raw
           $newContent = $content -replace '#define\s+mainCREATE_SIMPLE_BLINKY_DEMO_ONLY\s+0', '#define mainCREATE_SIMPLE_BLINKY_DEMO_ONLY    1'
           $newContent = $newContent -replace 'int\s+main(.*?)void(.*?)\r?\n\s*{', 'int main( void ){setvbuf( stdout, NULL, _IONBF, 0 );'
@@ -280,7 +280,7 @@ jobs:
         shell: bash
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           set +e
           git submodule update --checkout --init --depth 1 FreeRTOS/Source
           exitStatus=$?
@@ -298,7 +298,7 @@ jobs:
         shell: bash
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           set +e
           sudo apt-get -y update
           sudo apt-get -y install build-essential
@@ -319,7 +319,7 @@ jobs:
         working-directory: FreeRTOS/Demo/Posix_GCC
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           set +e
           sed -i -z "s/int[[:space:]]*main[[:space:]]*([[:space:]]*void[[:space:]]*)\n{/int main( void ){setvbuf( stdout, NULL, _IONBF, 0 );/g" main.c
           make -j
@@ -349,7 +349,7 @@ jobs:
         working-directory: FreeRTOS/Demo/Posix_GCC
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           rm -rf build
           set +e
           make -j USER_DEMO=BLINKY_DEMO
@@ -386,7 +386,7 @@ jobs:
         shell: bash
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           set +e
           git submodule update --checkout --init --depth 1 FreeRTOS/Source
           exitStatus=$?
@@ -404,7 +404,7 @@ jobs:
         shell: bash
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           set +e
           sudo apt-get -y update
           sudo apt-get -y install gcc-msp430 build-essential
@@ -424,7 +424,7 @@ jobs:
         working-directory: FreeRTOS/Demo/msp430_GCC
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           set +e
           make -j
           exitStatus=$?
@@ -445,13 +445,14 @@ jobs:
         name: ${{ env.stepName }}
         uses: actions/checkout@v3
 
+      
       - env:
           stepName: Fetch Kernel Submodule
         name: ${{ env.stepName }}
         shell: bash
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           set +e
           git submodule update --checkout --init --depth 1 FreeRTOS/Source FreeRTOS/Demo/ThirdParty/Community-Supported-Demos
           exitStatus=$?
@@ -469,7 +470,7 @@ jobs:
         shell: bash
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           set +e
           sudo apt-get -y update
           sudo apt-get -y install gcc-arm-none-eabi build-essential cmake git ninja-build python3-minimal
@@ -489,7 +490,7 @@ jobs:
         working-directory: FreeRTOS/Demo/CORTEX_MPU_M3_MPS2_QEMU_GCC
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           set +e
           make -j
           exitStatus=$?
@@ -508,8 +509,9 @@ jobs:
         working-directory: FreeRTOS/Demo/CORTEX_LM3S102_GCC
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           set +e
+          make clean
           make -j
           exitStatus=$?
           echo "::endgroup::"
@@ -527,7 +529,7 @@ jobs:
         working-directory: FreeRTOS/Demo/CORTEX_M3_MPS2_QEMU_GCC
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           set +e
           make clean
           make -j
@@ -547,7 +549,7 @@ jobs:
         working-directory: FreeRTOS/Demo/CORTEX_M3_MPS2_QEMU_GCC
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           set +e
           make clean
           make FULL_DEMO=1 -j
@@ -567,7 +569,7 @@ jobs:
         working-directory: FreeRTOS/Demo/CORTEX_LM3S811_GCC
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           set +e
           make -j
           exitStatus=$?
@@ -586,7 +588,7 @@ jobs:
         working-directory: FreeRTOS/Demo/ThirdParty/Community-Supported-Demos/CORTEX_M0+_RP2040
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           set +e
           git clone https://github.com/raspberrypi/pico-sdk.git
           cmake -B build -DPICO_SDK_PATH=pico-sdk -GNinja
@@ -607,7 +609,7 @@ jobs:
         working-directory: FreeRTOS/Demo/CORTEX_MPS2_QEMU_IAR_GCC
         run: |
           # ${{ env.stepName }}
-          echo "::group:: ${{ env.stepName }}"
+          echo "::group::${{ env.stepName }}"
           set +e
           make -C build/gcc -j
           exitStatus=$?
