Just a random attmept at running the qemu demo in the workflow to see if it works

diff --git a/.github/workflows/freertos_demos.yml b/.github/workflows/freertos_demos.yml
--- a/.github/workflows/freertos_demos.yml
+++ b/.github/workflows/freertos_demos.yml
@@ -516,6 +516,34 @@ jobs:
                   fi
 
             - env:
+                  stepName: Build Qemu Runner File
+              name: ${{ env.stepName }}
+              shell: bash
+              working-directory: .github/scripts
+              run: |
+                  # ${{ env.stepName }}
+                  echo "::group::${{ env.stepName }}"
+                  gcc qemu_reader.c -o ../../FreeRTOS/Demo/CORTEX_MPS2_QEMU_IAR_GCC/qemu_reader.out
+                  echo "::endgroup::"
+                  if [ $exitStatus -eq 0 ]; then
+                    echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+                  else
+                    echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+                    exit 1
+                  fi
+
+            - env:
+                  stepName:
+                      Run and monitor CORTEX_MPU_M3_MPS2_QEMU_GCC
+              name: ${{ env.stepName }}
+              uses: Skptak/CI-CD-GitHub-Actions/executable-monitor
+              with:
+                  exe-path: FreeRTOS/Demo/CORTEX_MPU_M3_MPS2_QEMU_GCC/qemu_reader.out
+                  timeout-seconds: 20
+                  success-line: "Message received from software timer"
+                  retry-attempts: 1
+
+            - env:
                   stepName: Build CORTEX_LM3S102_GCC Demo
               name: ${{ env.stepName }}
               shell: bash
